// Generated by https://pagedraw.io/pages/12763
import React from 'react';
import styled, {injectGlobal} from 'styled-components';

injectGlobal`
    @import url('https://fonts.googleapis.com/css?family=Montserrat:');
    
    * {
        box-sizing: border-box;
    }
    
    body {
        margin: 0;
    }
    
    button:hover {
        cursor: pointer;
    }
    
    a {
        text-decoration: none;
        color: inherit;
    }
    
    .pd-onhover-parent >.pd-onhover {
        display: none;
    }
    
    .pd-onhover-parent:hover > * {
        display: none;
    }
    
    .pd-onhover-parent:hover > .pd-onhover {
        display: flex;
    }
    
    .pd-onactive-parent > .pd-onactive {
        display: none;
    }
    
    .pd-onactive-parent:active > * {
        display: none;
    }
    
    .pd-onactive-parent:active > .pd-onactive {
        display: flex;
    }
    
    .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {
        display: none;
    }
`
const Main = styled.div`
    display: flex;
    flex-grow: 1;
`

const Main_mobhead_2 = styled.div`
    display: none;
    flex-direction: column;
    flex-grow: 1;
    background: #FFFFFF;
    min-height: 100vh;
    @media (max-width: 1007px) {
        display: flex;
    }
`

const Main_0_0 = styled.div`
    display: flex;
    flex-shrink: 0;
`

const Main_image_3 = styled.div`
    height: 246px;
    flex-grow: 1;
    flex-basis: 0px;
    background-size: cover;
    background-position: center;
`

const Main_0_1 = styled.div`
    display: flex;
    flex-shrink: 0;
    margin-top: 17px;
    padding-left: 16px;
`

const Main_h1 = styled.div`
    flex-grow: 0.9681697612732095;
    flex-basis: 0px;
    font-family: Futura, 'Trebuchet MS', Arial, sans-serif;
    color: rgba(0,0,0,1);
    font-size: 24px;
    line-height: 27px;
    letter-spacing: 0px;
    font-weight: 800;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
`

const Main_0_1_1 = styled.div`
    height: 0px;
    flex-grow: 0.03183023872679045;
    flex-basis: 0px;
`

const Main_0_2 = styled.div`
    display: flex;
    flex-shrink: 0;
    margin-top: 12px;
    padding-left: 16px;
`

const Main_views__1 = styled.div`
    flex-shrink: 0;
    font-family: "Montserrat", sans-serif;
    color: rgba(0,0,0,1);
    font-size: 18px;
    line-height: 21px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
    padding-right: 0.890625px;
`

const Main_viewnumber_6 = styled.div`
    flex-shrink: 0;
    margin-left: 4px;
    font-family: "Montserrat", sans-serif;
    color: rgba(0,0,0,1);
    font-size: 18px;
    line-height: 21px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: LEFT;
    word-wrap: break-word;
    padding-right: 0.078125px;
`

const Main_0_2_2 = styled.div`
    height: 0px;
    flex-grow: 1;
    flex-basis: 0px;
`

const Main_0_3 = styled.div`
    display: flex;
    flex-shrink: 0;
    margin-top: 21px;
    padding-left: 16px;
`

const Main_additional_info_0 = styled.div`
    flex-grow: 0.9602122015915119;
    flex-basis: 0px;
    font-family: "Montserrat", sans-serif;
    color: rgba(0,0,0,1);
    font-size: 18px;
    line-height: 21px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: justify;
    word-wrap: break-word;
`

const Main_0_3_1 = styled.div`
    height: 0px;
    flex-grow: 0.03978779840848806;
    flex-basis: 0px;
`

const Main_0_4 = styled.div`
    width: 0px;
    flex-shrink: 0;
    flex-grow: 1;
    flex-basis: 0px;
`

const Main_deskhead_2 = styled.div`
    display: none;
    flex-direction: column;
    flex-grow: 1;
    background: #FFFFFF;
    min-height: 100vh;
    @media (min-width: 1008px) {
        display: flex;
    }
`

const Main_1_0 = styled.div`
    display: flex;
    flex-shrink: 0;
`

const Main_image_8 = styled.div`
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    flex-basis: 0px;
    min-height: fit-content;
    padding-top: 64px;
    padding-bottom: 54px;
    background-size: cover;
    background-position: center;
`

const Main_1_0_0_0 = styled.div`
    display: flex;
    flex-shrink: 0;
    padding-left: 99px;
`

const Main_h1_ = styled.div`
    flex-grow: 0.49834983498349833;
    flex-basis: 0px;
    font-family: Futura, 'Trebuchet MS', Arial, sans-serif;
    color: rgba(0,0,0,1);
    font-size: 36px;
    line-height: 41px;
    letter-spacing: 0px;
    font-weight: 800;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
`

const Main_1_0_0_0_1 = styled.div`
    height: 0px;
    flex-grow: 0.5016501650165016;
    flex-basis: 0px;
`

const Main_1_0_0_1 = styled.div`
    display: flex;
    flex-shrink: 0;
    margin-top: 48px;
    padding-left: 99px;
`

const Main_views__6 = styled.div`
    flex-shrink: 0;
    font-family: "Montserrat", sans-serif;
    color: rgba(0,0,0,1);
    font-size: 18px;
    line-height: 21px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: left;
    word-wrap: break-word;
    padding-right: 0.296875px;
`

const Main_viewnumber_4 = styled.div`
    flex-shrink: 0;
    margin-left: 8px;
    font-family: "Montserrat", sans-serif;
    color: rgba(0,0,0,1);
    font-size: 18px;
    line-height: 21px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: LEFT;
    word-wrap: break-word;
    padding-right: 0.984375px;
`

const Main_1_0_0_1_2 = styled.div`
    height: 0px;
    flex-grow: 1;
    flex-basis: 0px;
`

const Main_1_0_0_2 = styled.div`
    display: flex;
    flex-shrink: 0;
    margin-top: 37px;
    padding-left: 99px;
`

const Main_additional_info_5 = styled.div`
    flex-grow: 0.9218921892189219;
    flex-basis: 0px;
    font-family: "Montserrat", sans-serif;
    color: rgba(0,0,0,1);
    font-size: 18px;
    line-height: 21px;
    letter-spacing: 0px;
    font-weight: normal;
    font-style: normal;
    text-decoration: none;
    text-align: justify;
    word-wrap: break-word;
`

const Main_1_0_0_2_1 = styled.div`
    height: 0px;
    flex-grow: 0.0781078107810781;
    flex-basis: 0px;
`

const Main_1_1 = styled.div`
    width: 0px;
    flex-shrink: 0;
    flex-grow: 1;
    flex-basis: 0px;
`

export default class M extends React.Component {
  render() {
    return (
      <Main>
          <Main_mobhead_2>
              <Main_0_0>
                  <Main_image_3 style={{"backgroundImage": ("url('"+(this.props.image)+"')")}} /> 
              </Main_0_0>
              <Main_0_1>
                  <Main_h1>{ this.props.title }</Main_h1>
                  <Main_0_1_1 /> 
              </Main_0_1>
              <Main_0_2>
                  <Main_views__1>{"Views:"}</Main_views__1>
                  <Main_viewnumber_6>
                      { this.props.viewNumber }
                  </Main_viewnumber_6>
                  <Main_0_2_2 /> 
              </Main_0_2>
              <Main_0_3>
                  <Main_additional_info_0>
                      { this.props.additional }
                  </Main_additional_info_0>
                  <Main_0_3_1 /> 
              </Main_0_3>
              <Main_0_4 /> 
          </Main_mobhead_2>
          <Main_deskhead_2>
              <Main_1_0>
                  <Main_image_8 style={{"backgroundImage": ("url('"+(this.props.image)+"')")}}>
                      <Main_1_0_0_0>
                          <Main_h1_>{ this.props.title }</Main_h1_>
                          <Main_1_0_0_0_1 /> 
                      </Main_1_0_0_0>
                      <Main_1_0_0_1>
                          <Main_views__6>{"Views:"}</Main_views__6>
                          <Main_viewnumber_4>
                              { this.props.viewNumber }
                          </Main_viewnumber_4>
                          <Main_1_0_0_1_2 /> 
                      </Main_1_0_0_1>
                      <Main_1_0_0_2>
                          <Main_additional_info_5>
                              { this.props.additional }
                          </Main_additional_info_5>
                          <Main_1_0_0_2_1 /> 
                      </Main_1_0_0_2>
                  </Main_image_8>
              </Main_1_0>
              <Main_1_1 /> 
          </Main_deskhead_2>
      </Main>
    );
  }
};
